export default Object.freeze({
    INVALID_UUID: "Invalid UUID",
    INVALID_TOKEN: "Invalid Token",
    TOKEN_EXPIRED: "Token Expired",
    INVALID_AUTH_TYPE: "Invalid Authorization Type",
    USER_PRIVATE_KEY_NOT_FOUND: "User Private Key Not Found",
    USER_PUBLIC_KEY_NOT_FOUND: "User Public Key Not Found",
    ANONYMOUS_PRIVATE_KEY_NOT_FOUND: "Anonymous Private Key Not Found",
    ANONYMOUS_PUBLIC_KEY_NOT_FOUND: "Anonymous Public Key Not Found",
    SYSTEM_PRIVATE_KEY_NOT_FOUND: "System Private Key Not Found",
    SYSTEM_PUBLIC_KEY_NOT_FOUND: "System Public Key Not Found",
    ADMIN_PRIVATE_KEY_NOT_FOUND: "Admin Private Key Not Found",
    ADMIN_PUBLIC_KEY_NOT_FOUND: "Admin Public Key Not Found",
    SECRET_TOKEN_NOT_FOUND: "Secret Token Not Found",
    ANONYMOUS_SESSION_NOT_ALLOWED: "Anonymous Session Not Allowed",
    USER_SESSION_NOT_ALLOWED: "User Session Not Allowed",
    SYSTEM_SESSION_NOT_ALLOWED: "System Session Not Allowed",
    CDN_SESSION_NOT_ALLOWED: "CDN Session Not Allowed",
    INTERNAL_SERVER_ERROR: "Internal Server Error"
})